services:
  tlsproxy:
    image: c2fmzq/tlsproxy:integrationtest
    user: "1000:1000"
    hostname: tlsproxy.example.com
    command: "--use-ephemeral-certificate-manager"
    volumes:
      - ./testdata/tlsproxy-config.yaml:/config/config.yaml:ro
      - ./testdata:/html:ro
      - ./sshterm/docroot:/sshterm:ro
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 10M
          mode: 0o1777
    networks:
      default:
        aliases:
          - www.example.com
          - photos.example.com
          - ssh.example.com

  photos-backend:
    image: c2fmzq/c2fmzq-server:integrationtest
    user: "1000:1000"
    hostname: photos-backend.example.com
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 10M
          mode: 0o1777
    environment:
      - C2FMZQ_ADDRESS=:8080
      - C2FMZQ_PASSPHRASE=test
      - C2FMZQ_PASSPHRASE_FILE=
      - C2FMZQ_DATABASE=/tmp/data

  mock-oidc-server:
    image: c2fmzq/mock-oidc-server:integrationtest
    user: "1000:1000"
    hostname: mock-oidc-server.example.com
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 10M
          mode: 0o1777

  mock-ssh-server:
    image: c2fmzq/mock-ssh-server:integrationtest
    user: "1000:1000"
    hostname: mock-ssh-server.example.com
    volumes:
      - ./testdata/mock_ssh_server_key:/mock_ssh_server_key:ro

  headless-shell:
    image: "chromedp/headless-shell:141.0.7390.37"
    user: "1000:1000"
    command: [
      "--ignore-certificate-errors",
    ]
    volumes:
      - type: tmpfs
        target: /nonexistent
        tmpfs:
          size: 10M
          mode: 0o777
      - ./testdata/test.jpg:/test.jpg

  devtests:
    image: c2fmzq/integration-tests:integrationtest
    user: "1000:1000"
    command: [
      "-test.v",
      "-test.timeout=5m",
    ]
    volumes:
      - ./testdata:/testdata:ro
      - ./output:/output
    depends_on:
      - tlsproxy
      - photos-backend
      - headless-shell
      - mock-oidc-server
      - mock-ssh-server

networks:
  default:
    internal: true
