services:
  inmemory-acme-server:
    image: c2fmzq/inmemory-acme-server:integrationtest
    user: "1000:1000"
    hostname: acme-v02.api.letsencrypt.org
    volumes:
      - tls:/etc/ssl/certs
    healthcheck:
      test: ["CMD", "/inmemory-acme-server", "--ready"]
      interval: 5s
      retries: 5
      start_period: 5s

  tlsproxy:
    image: c2fmzq/tlsproxy:integrationtest
    user: "1000:1000"
    hostname: tlsproxy.example.com
    command: "--passphrase=test"
    volumes:
      - tls:/etc/ssl/certs
      - ./testdata/tlsproxy-config.yaml:/config/config.yaml:ro
      - ./testdata/html:/html:ro
      - ./testdata/secure:/secure:ro
      - ./sshterm/docroot:/sshterm:ro
      - ./c2fmzq.org:/c2fmzq.org:ro
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 10M
          mode: 0o1777
    networks:
      default:
        aliases:
          - www.example.com
          - photos.example.com
          - c2fmzq.org
          - ssh.example.com
          - mock-backend.example.com
          - pki.example.com
          - secure.example.com
    depends_on:
      inmemory-acme-server:
        condition: service_healthy

  photos-backend:
    image: c2fmzq/c2fmzq-server:integrationtest
    user: "1000:1000"
    hostname: photos-backend.example.com
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 10M
          mode: 0o1777
    environment:
      - C2FMZQ_ADDRESS=:8080
      - C2FMZQ_PASSPHRASE=test
      - C2FMZQ_PASSPHRASE_FILE=
      - C2FMZQ_DATABASE=/tmp/data

  mock-oidc-server:
    image: c2fmzq/mock-oidc-server:integrationtest
    user: "1000:1000"
    hostname: mock-oidc-server.example.com
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 10M
          mode: 0o1777

  mock-ssh-server:
    image: c2fmzq/mock-ssh-server:integrationtest
    user: "1000:1000"
    hostname: mock-ssh-server.example.com
    volumes:
      - tls:/etc/ssl/certs:ro
      - ./testdata/mock_ssh_server_key:/mock_ssh_server_key:ro

  mock-backend-internal:
    image: c2fmzq/mock-backend:integrationtest
    user: "1000:1000"
    command: [
      "/backend", "--addr=:8443", "--jwks-url=https://www.example.com/jwks",
    ]
    volumes:
      - tls:/etc/ssl/certs:ro
    depends_on:
      - tlsproxy

  headless-shell:
    image: "chromedp/headless-shell:141.0.7390.37"
    user: "1000:1000"
    command: [
      "--ignore-certificate-errors",
    ]
    volumes:
      - type: tmpfs
        target: /nonexistent
        tmpfs:
          size: 10M
          mode: 0o1777
      - ./testdata/test.jpg:/test.jpg
      - download:/download

  devtests:
    image: c2fmzq/integration-tests:integrationtest
    user: "1000:1000"
    command: [
      "-test.v",
      "-test.timeout=10m",
      "-test.failfast",
    ]
    volumes:
      - ./testdata:/testdata:ro
      - tls:/etc/ssl/certs:ro
      - download:/download
      - ./output:/output
    depends_on:
      - tlsproxy
      - photos-backend
      - headless-shell
      - mock-oidc-server
      - mock-ssh-server

networks:
  default:
    internal: true

volumes:
  download:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "size=10M,uid=1000"
  tls:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "size=10M,uid=1000"
