name: Integration Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'tests/go.mod'

      - name: Run integration tests
        run: ./run-integration-tests.sh
